# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-23 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='id')),
                ('author', models.CharField(db_index=True, default='', max_length=100, verbose_name='\u6765\u6e90id')),
                ('content', models.TextField(default='', verbose_name='\u6765\u6e90\u540d\u5b57')),
            ],
        ),
    ]
