# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Huxiu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.IntegerField(default=0, verbose_name='\u65f6\u95f4'),
        ),
    ]
